version: 1.0
runtime: python3
runtime_version: 3.11
build:
  requirements_file: requirements.txt
  cache_build_dependencies: # Configures caching (for faster deployments!)
    enabled: true # Toggles caching
    watched_files: # List of files that will trigger a full rebuild of the Structure
      - requirements.txt
run:
  main_file: researcher.py
